version: "3"
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432 
    environment:
      DBNAME: default_database
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      default:

  backend:
    image: murthy95/sklearn-deployment-backend:latest
    container_name: backend
    environment:
      DBNAME: default_database
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: postgres
      MODEL_PATH: /api/model_artifacts/model.pkl
      SCALER_PATH: /api/model_artifacts/scaler.pkl
      LE_PATH: /api/model_artifacts/label_encoder.pkl
      MODEL_KEY: 1234567890
    depends_on:
      - postgres
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python /api/main.py'
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      default:
  
  frontend:
    image: murthy95/sklearn-deployment-frontend:latest
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BASE_URL: http://localhost:8000/
      PUBLIC_URL: http://localhost:3000/
    networks:
      default:

networks:
  default:
    driver: bridge

volumes:
  data:
  config:
  bin:
